version: '3.5'
services:
    tx-app:
        build: .
        depends_on:
            - rx-app-1
        #network_mode: host
        entrypoint: ["/root/app/mcast.py", "tx", "-m", "Sending", "-l", "60"]
        networks:
            mcast:
                ipv4_address: 172.16.238.10
    
    rx-app-1:
        build: .
        #network_mode: host
        entrypoint: ["/root/app/mcast.py", "rx"]
        networks:
            mcast:
                ipv4_address: 172.16.238.11

    rx-app-2:
        build: .
        #network_mode: host
        entrypoint: ["/root/app/mcast.py", "rx"]
        networks:
            mcast:
                ipv4_address: 172.16.238.12

    rx-app-3:
        build: .
        #network_mode: host
        entrypoint: ["/root/app/mcast.py", "rx"]
        networks:
            mcast:
                ipv4_address: 172.16.238.13

            
networks:
    mcast:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.16.238.0/24"
